In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'Understand the meaning of words',
    'your videos are good'
]

In [6]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [7]:
#Define the vocab size and convert into verctor
vac_size = 10000

In [8]:
# one Hot Representation
one_hot_repr = [one_hot(words, vac_size)for words in sent]
one_hot_repr

[[9946, 1940, 6182, 3593],
 [9946, 1940, 6182, 258],
 [9946, 8253, 6182, 7494],
 [749, 7280, 8858, 439, 5926],
 [749, 7280, 8858, 439, 3289],
 [8145, 9946, 3411, 6182, 1545],
 [2763, 9368, 7784, 439]]

In [9]:

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sen_len = 8
embedded_doc = pad_sequences(one_hot_repr,padding='pre',maxlen=sen_len)
print(embedded_doc)

[[   0    0    0    0 9946 1940 6182 3593]
 [   0    0    0    0 9946 1940 6182  258]
 [   0    0    0    0 9946 8253 6182 7494]
 [   0    0    0  749 7280 8858  439 5926]
 [   0    0    0  749 7280 8858  439 3289]
 [   0    0    0 8145 9946 3411 6182 1545]
 [   0    0    0    0 2763 9368 7784  439]]


In [12]:
## Feature representation 
dim = 10

In [13]:
model = Sequential()
model.add(Embedding(vac_size,dim,input_length=sen_len))
model.compile('adam','mse')

c:\Users\HP\Downloads\rnn_sentiment-main\rnn_sentiment-main\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 772ms/step


array([[[-0.03890873,  0.00297135,  0.02047992, -0.04107801,
         -0.02157348,  0.02782894, -0.03718068, -0.03330272,
          0.0420226 , -0.00872242],
        [-0.03890873,  0.00297135,  0.02047992, -0.04107801,
         -0.02157348,  0.02782894, -0.03718068, -0.03330272,
          0.0420226 , -0.00872242],
        [-0.03890873,  0.00297135,  0.02047992, -0.04107801,
         -0.02157348,  0.02782894, -0.03718068, -0.03330272,
          0.0420226 , -0.00872242],
        [-0.03890873,  0.00297135,  0.02047992, -0.04107801,
         -0.02157348,  0.02782894, -0.03718068, -0.03330272,
          0.0420226 , -0.00872242],
        [-0.01314553, -0.04492512,  0.03615875, -0.03933483,
          0.00163431, -0.01851662,  0.0193751 ,  0.01444644,
         -0.00986078,  0.00720488],
        [-0.04872564, -0.03941343,  0.03830903, -0.02490305,
          0.0273282 ,  0.04550606, -0.01973638, -0.03035188,
         -0.00135935,  0.01949345],
        [-0.04716697, -0.03233333, -0.00596778,  0.0